version: 2
updates:
  # Wykop Index function
  - package-ecosystem: "npm"
    directory: "/functions/wykop-index"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      # group version updates to all dependencies into a single PR
      update-all:
        applies-to: version-updates
        patterns:
          - "*"
      # group security updates to all dependencies into a single PR
      security-all:
        applies-to: security-updates
        patterns:
          - "*"

  # Wykop Post function
  - package-ecosystem: "npm"
    directory: "/functions/wykop-post"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      update-all:
        applies-to: version-updates
        patterns:
          - "*"
      security-all:
        applies-to: security-updates
        patterns:
          - "*"

  # WykopIndex site
  - package-ecosystem: "npm"
    directory: "/sites/WykopIndex"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      update-all:
        applies-to: version-updates
        patterns:
          - "*"
      security-all:
        applies-to: security-updates
        patterns:
          - "*"
